name: CI workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-bundle:
    name: "Validate Databricks Asset Bundle"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Validate Bundle Configuration
        working-directory: bicycle_riding
        run: databricks bundle validate
        env:
          DATABRICKS_HOST: ${{ FIRST_SECRET.https://dbc-26ed86fb-114b.cloud.databricks.com/browse/folders/1388272585228683?o=7474655166986599 }}
          DATABRICKS_TOKEN: ${{ FIRST_SECRET.dapia0f13deb634d760ba0e5b484ad11b0e9 }}
